### ISSUE TITLE
install error? No Route Registered

### ISSUE THREAD

**Issue by johnnliu** [jakkaj/funcgraph#1]
![image](https://cloud.githubusercontent.com/assets/1279372/24827710/a9cd2008-1c92-11e7-891f-84a008aa3fad.png)

**Comment by johnnliu** [comment]
quick update - I went away and come back, may be the appservice resetted?  but now it's showing.

**Comment by paulbatum** [comment]
You need to restart the site after installing the extension. Hit the button at the top right.

**Comment by jakkaj** [comment]
@paulbatum - cheers for that. @johnnliu also a precautionary FYI - they wont install at all in consumption based plans.
